package com.itez.vghtc.util;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.annotations.PropertyId;
import com.vaadin.ui.BrowserFrame;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.DateField;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ApplyForm extends VerticalLayout {
	protected Panel panelProfile;
	@PropertyId("personNameEn")
	protected TextField txtPersonNameEn;
	@PropertyId("personNameCh")
	protected TextField txtPersonNameCh;
	@PropertyId("passportNo")
	protected TextField txtPassportNo;
	protected ComboBox<com.itez.vghtc.util.Nation> combNation;
	@PropertyId("gender")
	protected RadioButtonGroup<java.lang.String> rbgGender;
	protected DateField dateBirth;
	@PropertyId("roleStatus")
	protected RadioButtonGroup<java.lang.String> rbgRoleStatus;
	@PropertyId("elseRole")
	protected TextField txtElseRole;
	@PropertyId("affiliation")
	protected TextField txtAffiliation;
	protected ComboBox<com.itez.vghtc.util.Nation> combSchoolLocation;
	protected Panel panelChinese;
	@PropertyId("chListening")
	protected RadioButtonGroup<java.lang.String> rbgChListening;
	@PropertyId("chSpeaking")
	protected RadioButtonGroup<java.lang.String> rbgChSpeaking;
	@PropertyId("chReading")
	protected RadioButtonGroup<java.lang.String> rbgChReading;
	@PropertyId("chWriting")
	protected RadioButtonGroup<java.lang.String> rbgChWriting;
	protected Panel panelContact;
	@PropertyId("email")
	protected TextField txtEmail;
	@PropertyId("mailAddress")
	protected TextField txtMailAddress;
	@PropertyId("phoneNo")
	protected TextField txtPhoneNo;
	@PropertyId("contactName")
	protected TextField txtContactName;
	@PropertyId("contactRelation")
	protected TextField txtContactRelation;
	@PropertyId("contactAddress")
	protected TextField txtContactAddress;
	@PropertyId("contactPhone")
	protected TextField txtContactPhone;
	protected Panel panelChoiceOfDivi;
	@PropertyId("trainGoal")
	protected TextArea txtTrainGoal;
	@PropertyId("interestField")
	protected TextArea txtInterestField;
	protected GridLayout gridlayoutChoice;
	protected VerticalLayout layoutRowChoice;
	protected ComboBox<com.itez.vghtc.util.Dept> combDept;
	protected ComboBox<com.itez.vghtc.util.Divi> combDivi;
	protected DateField dateFromChoice;
	protected DateField dateEndChoice;
	protected CssLayout csslayoutTeacher1;
	protected TextField txtTeacherNameEn1;
	protected TextField txtTeacherNameCh1;
	protected TextField txtTeacherEmail1;
	protected TextField txtTeacherPhone1;
	protected CssLayout csslayoutTeacher2;
	protected TextField txtTeacherNameEn2;
	protected TextField txtTeacherNameCh2;
	protected TextField txtTeacherEmail2;
	protected TextField txtTeacherPhone2;
	protected CssLayout csslayoutTeacher3;
	protected TextField txtTeacherNameEn3;
	protected TextField txtTeacherNameCh3;
	protected TextField txtTeacherEmail3;
	protected TextField txtTeacherPhone3;
	protected Button btnNewChoice;
	protected HorizontalLayout layoutTuition;
	protected Panel panelCovid;
	protected GridLayout gridlayoutVacci;
	protected VerticalLayout layoutRowVacci;
	protected DateField dateVaccin;
	protected TextField txtPlaceVacci;
	protected ComboBox<java.lang.String> combVender;
	protected TextField txtElseVender;
	protected Button btnNewVacci;
	protected BrowserFrame frameCovid;
	protected Panel panelAccomm;
	@PropertyId("accommType")
	protected RadioButtonGroup<java.lang.String> rbgAccommdation;
	protected Panel panelSupportingDocs;
	protected BrowserFrame framePhoto;
	protected BrowserFrame framePassport;
	protected BrowserFrame framelicensure;
	protected BrowserFrame frameDiploma;
	protected BrowserFrame frameRecommend;
	protected BrowserFrame frameCV;
	protected BrowserFrame frameHealthCheck;
	protected Panel panelFlight;
	protected BrowserFrame frameFlight;
	protected BrowserFrame frameInsurance;
	protected Button btnSave;
	protected Button btnSubmit;

	public ApplyForm() {
		Design.read(this);
	}
}
